#pragma once
// LogFinder: Display: Step: 0x14c2a70
//LogFinder : Display : StepExplicitProperty : 0x14c2aa0
//LogFinder : Display : CreateNetDriver : 0x2501480
//LogFinder : Display : InitListen : 0x345650
//LogFinder : Display : SetWorld : 0x22b56f0
//LogFinder : Display : GetNetMode : 0x2559520
//LogFinder : Display : TickFlush : 0x22b6ab0
//LogFinder : Display : GetMaxTickRate : 0x2508650
//LogFinder : Display : DispatchRequest : 0x7f2370
//LogFinder : Display : Realloc : 0x1280550
//LogFinder : Display : StaticFindObject : 0x14e5890
//LogFinder : Display : StaticLoadObject : 0x14e7390
//LogFinder : Display : GIsClient : 0x4a9ca14
//LogFinder : Display : GameSessionPatch : 0x9eb786
//LogFinder : Display : EncryptionPatch : 0x255bb1e
// Generated by Sarah's Offset Finder - https://github.com/plooshi/SkidFinder
// Fortnite version: 3.6
#include <stdint.h>
#include <array>
namespace SDK {
    class UNetDriver;
    class UObject;
    class UClass;
    class UField;
    class FField;
    class UEngine;
    class FName;
    struct FURL;
    class UReplicationDriver;
    class UWorld;
    class AOnlineBeaconHost;
};
namespace UC {
    class FString;
}
class FFrame;

namespace Sarah {
    inline auto ImageBase = *(uint64_t*)(__readgsqword(0x60) + 0x10);
    namespace Offsets {
        inline uint64_t Step = 0x14c2a70;
        inline uint64_t StepExplicitProperty = 0x14c2aa0;
        inline uint64_t CreateNetDriver = 0x2501480;
        inline uint64_t InitListen = 0x345650;
        inline uint64_t SetWorld = 0x22b56f0;
        inline uint64_t GetNetMode = 0x2559520;
        inline uint64_t TickFlush = 0x22b6ab0;
        inline uint64_t GetMaxTickRate = 0x2508650;
        inline uint64_t DispatchRequest = 0x7f2370;
        inline uint64_t Realloc = 0x1280550;
        inline uint64_t StaticFindObject = 0x14e5890;
        inline uint64_t StaticLoadObject = 0x14e7390;
        inline uint64_t GIsClient = 0x4a9ca14;
        inline uint64_t GameSessionPatch = 0x9eb786;
        inline uint64_t EncryptionPatch = 0x255bb1e;
        inline std::array<uint64_t, 4> NullFuncs = { 0xa767b0, 0xc22e90, 0xd772c0 };
        inline std::array<uint64_t, 0> RetTrueFuncs = {  };
    };

    namespace Vfts {
    };

    namespace Funcs {
        inline auto Step = (void (*)(FFrame*, SDK::UObject*, void* const)) (ImageBase + Offsets::Step);
        inline auto StepExplicitProperty = (void (*)(FFrame*, void* const, SDK::UField*)) (ImageBase + Offsets::StepExplicitProperty);
        inline auto CreateNetDriver = (SDK::UNetDriver * (*)(SDK::UEngine*, SDK::UWorld*, SDK::FName)) (ImageBase + Offsets::CreateNetDriver);
        inline auto InitListen = (bool (*)(SDK::UNetDriver*, SDK::UWorld*, SDK::FURL&, bool, UC::FString&)) (ImageBase + Offsets::InitListen);
        inline auto SetWorld = (void (*)(SDK::UNetDriver*, SDK::UWorld*)) (ImageBase + Offsets::SetWorld);
        inline auto Realloc = (void* (*)(void*, __int64, unsigned int)) (ImageBase + Offsets::Realloc);
        inline auto StaticFindObject = (SDK::UObject * (*)(SDK::UClass*, SDK::UObject*, const wchar_t*, bool)) (ImageBase + Offsets::StaticFindObject);
        inline auto StaticLoadObject = (SDK::UObject * (*)(SDK::UClass*, SDK::UObject*, const wchar_t*, const wchar_t*, uint32_t, SDK::UObject*, bool)) (ImageBase + Offsets::StaticLoadObject);
    };
};
using namespace Sarah;
using namespace Sarah::Offsets;
using namespace Sarah::Vfts;
using namespace Sarah::Funcs;
